CREATE USER USER_KAMIL IDENTIFIED BY USER_PASSWORD;
GRANT CONNECT, RESOURCE TO USER_KAMIL;
CREATE TABLESPACE TS_UTILS_DATA DATAFILE 'TS_UTILS_DATA.DBF' SIZE 120M AUTOEXTEND ON NEXT 20M MAXSIZE 2048M;
CREATE TABLESPACE TS_UTILS_IDX DATAFILE 'TS_UTILS_IDX.DBF' SIZE 20M AUTOEXTEND ON NEXT 20M MAXSIZE 2048M;
ALTER TABLE USER_KAMIL DEFAULT TABLESPACE TS_UTILS_DATA;
ALTER TABLE USER_KAMIL QUOTA UNLIMITED ON TS_UTILS_DATA;
ALTER TABLE USER_KAMIL QUOTA UNLIMITED ON TS_UTILS_IDX;

GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO USER_KAMIL;
GRANT SELECT ON SYS.PENDING_TRANS$ TO USER_KAMIL;
GRANT SELECT ON SYS.DBA_2PC_PENDING TO USER_KAMIL;
GRANT EXECUTE ON SYS.DBMS_XA TO USER_KAMIL;
GRANT FORCE ANY TRANSACTION TO USER_KAMIL;
