version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql_j11t9
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zwroty_e_strix_com
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      app_net5:
        ipv4_address: 10.99.105.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma_j11t9
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    networks:
      app_net5:
        ipv4_address: 10.99.105.3

  tomcat:
    image: estrix/tomcat
    container_name: tomcat9
    build: ./docker/tomcat
    volumes:
#      - ./war/tomcat/:/opt/tomcat/webapps/
      - ./logs/tomcat/:/opt/tomcat/logs/
    environment:
      - TOMCAT_USER=root
      - TOMCAT_PASSWORD=password
    ports:
      - 8082:8080
      - 8443:8443
    networks:
      app_net5:
        ipv4_address: 10.99.105.4

networks:
  app_net5:
    ipam:
      driver: default
      config:
        - subnet: "10.99.105.0/24"
